### ISSUE TITLE
use fgit pull

### ISSUE THREAD

**Issue by a5601564** [FastGitORG/fgit-go#11]
[fgit] 程序崩溃, 错误原因: JSON反序列化失败: {"key":"ACCOUNT_NOT_FOUND"}
: json: cannot unmarshal object into Go value of type string

**Comment by KevinZonda** [comment]
嗨，请问是怎么复现 的呢？

**Comment by a5601564** [comment]
就 直接 使用 fgit pull ,就出现这个错误了.

**Comment by KevinZonda** [comment]
嗨！感谢你的反馈。我将会定位问题。我会很感激如果你能能提供原始错误信息。

如果你确信错误信息包含中文，我们可能需要检查pull的指令生成以及最后调用git的结果。我暂时不能判定错误。

19 Apr 2021, 09:48 by ***@***.***:

**Comment by a5601564** [comment]
以前使用没有问题，今天查看服务器发现了这个问题。了解，谢谢。

**Comment by KevinZonda** [comment]
感谢你的反馈！如果错误持续，请随时联系我或重新打开issue。
